version: '3.5'

services:

  database:
    container_name: database
    image: postgres
    env_file:
      - database.env
    volumes:
       - postgres-data:/var/lib/postgresql/data
    ports:
      - "8888:5432"
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn dev
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 8080:3000
    depends_on:
      - database

volumes:
  postgres-data: