version: '3.5'

services:

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - database.env
    volumes:
       - postgres-data:/var/lib/postgresql/data
    ports:
      - "8888:5432"
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    command: node server.js
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - adminer

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: adminer

volumes:
  postgres-data: