version: '3.5'

services:

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - database.env
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "8888:5432"
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: adminer